/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisfoprojectmanagement.view;

import java.awt.event.ActionListener;
import javax.swing.JLabel;

/**
 *
 * @author gridd
 */
public class HalamanAwalProgrammer extends javax.swing.JFrame {

    /**
     * Creates new form HalamanAwalProgramer
     */
    public HalamanAwalProgrammer() {
        initComponents();
        
 this.setLocationRelativeTo(null);
        this.setTitle("Haaman Awal Programmer");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LNamaTugas1 = new javax.swing.JLabel();
        LDeadline1 = new javax.swing.JLabel();
        LDeskripsi1 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        LNamaProyek1 = new javax.swing.JLabel();
        BtnTS1 = new javax.swing.JButton();
        Jpanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        LNamaTugas2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        LDeadline2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        LDeskripsi2 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        LNamaProyek2 = new javax.swing.JLabel();
        BtnTS2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        LNamaTugas3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        LDeadline3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        LDeskripsi3 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        LNamaProyek3 = new javax.swing.JLabel();
        BtnTS3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        LNamaTugas4 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        LDeadline4 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        LDeskripsi4 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        LNamaProyek4 = new javax.swing.JLabel();
        BtnTS4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tugas 1"));

        jLabel1.setText("Nama Tugas");

        jLabel2.setText("Deadline");

        jLabel3.setText("Deskripsi");

        jLabel4.setText(":");

        jLabel5.setText(":");

        jLabel6.setText(":");

        LNamaTugas1.setText("jLabel7");

        LDeadline1.setText("jLabel8");

        LDeskripsi1.setText("jLabel9");

        jLabel37.setText("Nama Proyek");

        jLabel38.setText(":");

        LNamaProyek1.setText("jLabel39");

        BtnTS1.setText("Tugas Selesai");
        BtnTS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTS1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LDeskripsi1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(LDeadline1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(LNamaTugas1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LNamaProyek1)
                .addGap(77, 77, 77))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnTS1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38)
                    .addComponent(LNamaProyek1)
                    .addComponent(LNamaTugas1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(LDeadline1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(LDeskripsi1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnTS1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LNamaTugas1.getAccessibleContext().setAccessibleName("LNamaTugas1");
        LDeadline1.getAccessibleContext().setAccessibleName("LDeadline1");
        LDeskripsi1.getAccessibleContext().setAccessibleName("LDeskripsi1");
        LNamaProyek1.getAccessibleContext().setAccessibleName("LNamaProyek1");

        Jpanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tugas 2"));

        jLabel10.setText("Nama Tugas");

        jLabel11.setText(":");

        LNamaTugas2.setText("jLabel12");

        jLabel13.setText("Deadline");

        jLabel14.setText(":");

        LDeadline2.setText("jLabel15");

        jLabel16.setText("Deskripsi");

        jLabel17.setText(":");

        LDeskripsi2.setText("jLabel18");

        jLabel40.setText("Nama Proyek");

        jLabel41.setText(":");

        LNamaProyek2.setText("jLabel42");

        BtnTS2.setText("Tugas Selesai");

        javax.swing.GroupLayout Jpanel2Layout = new javax.swing.GroupLayout(Jpanel2);
        Jpanel2.setLayout(Jpanel2Layout);
        Jpanel2Layout.setHorizontalGroup(
            Jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Jpanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LDeskripsi2))
                    .addGroup(Jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(Jpanel2Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(LDeadline2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Jpanel2Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(LNamaTugas2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LNamaProyek2)
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnTS2)
                .addContainerGap())
        );
        Jpanel2Layout.setVerticalGroup(
            Jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(LNamaTugas2)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41)
                    .addComponent(LNamaProyek2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(LDeadline2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(LDeskripsi2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnTS2)
                .addContainerGap())
        );

        LNamaTugas2.getAccessibleContext().setAccessibleName("LNamaTugas2");
        LDeadline2.getAccessibleContext().setAccessibleName("LDeadline2");
        LDeskripsi2.getAccessibleContext().setAccessibleName("LDeskripsi2");
        LNamaProyek2.getAccessibleContext().setAccessibleName("LNamaProyek2");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tugas 3"));

        jLabel19.setText("Nama Tugas");

        jLabel20.setText(":");

        LNamaTugas3.setText("jLabel21");

        jLabel22.setText("Deadline");

        jLabel23.setText(":");

        LDeadline3.setText("jLabel24");

        jLabel25.setText("Deskripsi");

        jLabel26.setText(":");

        LDeskripsi3.setText("jLabel27");

        jLabel43.setText("Nama Proyek");

        jLabel44.setText(":");

        LNamaProyek3.setText("jLabel45");

        BtnTS3.setText("Tugas Selesai");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LDeskripsi3))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(LDeadline3))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(LNamaTugas3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnTS3)
                    .addComponent(LNamaProyek3))
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(LNamaTugas3)
                    .addComponent(jLabel43)
                    .addComponent(jLabel44)
                    .addComponent(LNamaProyek3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(LDeadline3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(LDeskripsi3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnTS3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LNamaTugas3.getAccessibleContext().setAccessibleName("LNamaTugas3");
        LDeadline3.getAccessibleContext().setAccessibleName("LDeadline3");
        LDeskripsi3.getAccessibleContext().setAccessibleName("LDeskripsi3");
        LNamaProyek3.getAccessibleContext().setAccessibleName("LNamaProyek3");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tugas 4"));

        jLabel28.setText("Nama Tugas");

        jLabel29.setText(":");

        LNamaTugas4.setText("jLabel30");

        jLabel31.setText("Deadline");

        jLabel32.setText(":");

        LDeadline4.setText("jLabel33");

        jLabel34.setText("Deskripsi");

        jLabel35.setText(":");

        LDeskripsi4.setText("jLabel36");

        jLabel46.setText("Nama Proyek");

        jLabel47.setText(":");

        LNamaProyek4.setText("jLabel48");

        BtnTS4.setText("Tugas Selesai");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel32))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LDeadline4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LDeskripsi4, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LNamaTugas4)
                                .addGap(193, 193, 193)
                                .addComponent(jLabel46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel47)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnTS4)
                                    .addComponent(LNamaProyek4)))))
                    .addComponent(jLabel34))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(LNamaTugas4)
                    .addComponent(jLabel46)
                    .addComponent(jLabel47)
                    .addComponent(LNamaProyek4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(LDeadline4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35)
                    .addComponent(LDeskripsi4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnTS4)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        LNamaTugas4.getAccessibleContext().setAccessibleName("LNamaTugas4");
        LDeadline4.getAccessibleContext().setAccessibleName("LDeadline4");
        LDeskripsi4.getAccessibleContext().setAccessibleName("LDeskripsi4");
        LNamaProyek4.getAccessibleContext().setAccessibleName("LNamaProyek4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jpanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Jpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTS1ActionPerformed

    public JLabel getLDeadline1() {
        return LDeadline1;
    }

    public void setLDeadline1(JLabel LDeadline1) {
        this.LDeadline1 = LDeadline1;
    }

    public JLabel getLDeadline2() {
        return LDeadline2;
    }

    public void setLDeadline2(JLabel LDeadline2) {
        this.LDeadline2 = LDeadline2;
    }

    public JLabel getLDeadline3() {
        return LDeadline3;
    }

    public void setLDeadline3(JLabel LDeadline3) {
        this.LDeadline3 = LDeadline3;
    }

    public JLabel getLDeadline4() {
        return LDeadline4;
    }

    public void setLDeadline4(JLabel LDeadline4) {
        this.LDeadline4 = LDeadline4;
    }

    public JLabel getLDeskripsi1() {
        return LDeskripsi1;
    }

    public void setLDeskripsi1(JLabel LDeskripsi1) {
        this.LDeskripsi1 = LDeskripsi1;
    }

    public JLabel getLDeskripsi2() {
        return LDeskripsi2;
    }

    public void setLDeskripsi2(JLabel LDeskripsi2) {
        this.LDeskripsi2 = LDeskripsi2;
    }

    public JLabel getLDeskripsi3() {
        return LDeskripsi3;
    }

    public void setLDeskripsi3(JLabel LDeskripsi3) {
        this.LDeskripsi3 = LDeskripsi3;
    }

    public JLabel getLDeskripsi4() {
        return LDeskripsi4;
    }

    public void setLDeskripsi4(JLabel LDeskripsi4) {
        this.LDeskripsi4 = LDeskripsi4;
    }

    public JLabel getLNamaProyek1() {
        return LNamaProyek1;
    }

    public void setLNamaProyek1(JLabel LNamaProyek1) {
        this.LNamaProyek1 = LNamaProyek1;
    }

    public JLabel getLNamaProyek2() {
        return LNamaProyek2;
    }

    public void setLNamaProyek2(JLabel LNamaProyek2) {
        this.LNamaProyek2 = LNamaProyek2;
    }

    public JLabel getLNamaProyek3() {
        return LNamaProyek3;
    }

    public void setLNamaProyek3(JLabel LNamaProyek3) {
        this.LNamaProyek3 = LNamaProyek3;
    }

    public JLabel getLNamaProyek4() {
        return LNamaProyek4;
    }

    public void setLNamaProyek4(JLabel LNamaProyek4) {
        this.LNamaProyek4 = LNamaProyek4;
    }

    public JLabel getLNamaTugas1() {
        return LNamaTugas1;
    }

    public void setLNamaTugas1(JLabel LNamaTugas1) {
        this.LNamaTugas1 = LNamaTugas1;
    }

    public JLabel getLNamaTugas2() {
        return LNamaTugas2;
    }

    public void setLNamaTugas2(JLabel LNamaTugas2) {
        this.LNamaTugas2 = LNamaTugas2;
    }

    public JLabel getLNamaTugas3() {
        return LNamaTugas3;
    }

    public void setLNamaTugas3(JLabel LNamaTugas3) {
        this.LNamaTugas3 = LNamaTugas3;
    }

    public JLabel getLNamaTugas4() {
        return LNamaTugas4;
    }

    public void setLNamaTugas4(JLabel LNamaTugas4) {
        this.LNamaTugas4 = LNamaTugas4;
    }
    
  public void addListener(ActionListener e){
        BtnTS1.addActionListener(e);
        BtnTS2.addActionListener(e);
        BtnTS3.addActionListener(e);
        BtnTS4.addActionListener(e);
    }

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnTS1;
    private javax.swing.JButton BtnTS2;
    private javax.swing.JButton BtnTS3;
    private javax.swing.JButton BtnTS4;
    private javax.swing.JPanel Jpanel2;
    private javax.swing.JLabel LDeadline1;
    private javax.swing.JLabel LDeadline2;
    private javax.swing.JLabel LDeadline3;
    private javax.swing.JLabel LDeadline4;
    private javax.swing.JLabel LDeskripsi1;
    private javax.swing.JLabel LDeskripsi2;
    private javax.swing.JLabel LDeskripsi3;
    private javax.swing.JLabel LDeskripsi4;
    private javax.swing.JLabel LNamaProyek1;
    private javax.swing.JLabel LNamaProyek2;
    private javax.swing.JLabel LNamaProyek3;
    private javax.swing.JLabel LNamaProyek4;
    private javax.swing.JLabel LNamaTugas1;
    private javax.swing.JLabel LNamaTugas2;
    private javax.swing.JLabel LNamaTugas3;
    private javax.swing.JLabel LNamaTugas4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
